apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
    project: task-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    project: task-manager
