apiVersion: v1
kind: Secret
metadata:
  name: taskapi-secret
  namespace: app
type: Opaque
# Values are base64 encoded
# mongodb://localhost:27017/taskmanager → base64
data:
  # mongodb://173.249.11.198:27017/taskmanager
  MONGODB_URI: bW9uZ29kYjovLzE3My4yNDkuMTEuMTk4OjI3MDE3L3Rhc2ttYW5hZ2Vy
