apiVersion: v1
kind: Service
metadata:
  name: taskapi-service
  namespace: app
  labels:
    app: taskapi
spec:
  selector:
    app: taskapi
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
